version: '3.8'

services:
  node_exporter:
    image: prom/node-exporter:latest
    expose:
      - 9100
    restart: unless-stopped
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"
    pid: host
    networks:
      monitor-network:
        aliases:
          - node_exporter

  cadvisor:
    image: google/cadvisor:latest
    expose:
      - 8080
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    networks:
      monitor-network:
        aliases:
          - cadvisor

  prometheus:
    image: prom/prometheus:latest
    expose:
      - 9090
    restart: unless-stopped
    volumes:
        - "./prometheus.yml:/etc/prometheus/prometheus.yml"
        - prometheus-storage:/prometheus
    command:
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=5GB'
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - "node_exporter"
      - "cadvisor"
    networks:
      monitor-network:
        aliases:
          - prometheus

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    expose:
      - 3100
    volumes:
      - loki-storage:/loki
    networks:
      monitor-network:
        aliases:
          - loki

  promtail:
    image: grafana/promtail
    restart: unless-stopped
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      monitor-network:
        aliases:
          - promtail

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      monitor-network:
        aliases:
          - grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    
# Network
networks:
  monitor-network:
    driver: bridge

# Volumes
volumes:
  prometheus-storage:
  grafana-storage:
  loki-storage:
