services:
  node_exporter:
    image: prom/node-exporter:latest
    expose:
      - 9100
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
    pid: host
    networks:
      monitor-network:
        aliases:
          - node_exporter
    env_file:
      - ./.env

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    expose:
      - 8080
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    networks:
      monitor-network:
        aliases:
          - cadvisor
    env_file:
      - ./.env

  api-gateway:
    image: nginx:stable-alpine
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api-gateway/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - ${NODE_EXPORTER_PORT}:9100
      - ${CADVISOR_PORT}:8080
    restart: unless-stopped
    networks:
      monitor-network:
        aliases:
          - api-gateway
    env_file:
      - ./.env

# Network
networks:
  monitor-network:
    driver: bridge