services:
  node_exporter:
    image: prom/node-exporter:latest
    expose:
      - 9100
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
    pid: host
    networks:
      monitor-network:
        aliases:
          - node_exporter

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    expose:
      - 8080
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    networks:
      monitor-network:
        aliases:
          - cadvisor

  prometheus:
    image: prom/prometheus:latest
    expose:
      - 9090
    restart: unless-stopped
    volumes:
        - "./prometheus.yml:/etc/prometheus/prometheus.yml"
        - prometheus-storage:/prometheus
    command:
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=5GB'
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      monitor-network:
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      monitor-network:
        aliases:
          - grafana
    volumes:
      - grafana-storage:/var/lib/grafana

# Network
networks:
  monitor-network:
    driver: bridge

# Volumes
volumes:
  prometheus-storage:
    driver: local
    driver_opts:
      type: none
      device: ./data/prometheus
      o: bind
  grafana-storage:
    driver: local
    driver_opts:
      type: none
      device: ./data/grafana
      o: bind
