[SERVICE]
    flush        5
    daemon       off
    log_level    info
    parsers_file /fluent-bit/etc/parsers.conf

# accept http post json
[INPUT]
    name              http
    listen            0.0.0.0
    port              3100
    tag               http.json

# send to loki
[OUTPUT]
    name              loki
    match             http.json
    host              loki
    port              3100
    labels            job=fluentbit,method=$request['method'],service=$service['name'],route=$route['name'],status=$response['status']
    # line_format       json